name: 'build-test'
on:
  workflow_dispatch:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get pipeline status
        uses: ./
      - name: Gives a conclusion
        run: |
          if [[ "${{ env.WORKFLOW_CONCLUSION }}" != "skipped" ]]; then echo "The pipeline failed" && exit 1; fi
